---
title: "Data wrangling"
author: "Laurel"
date: "October 22, 2018"
output: html_document
---



```{r}
library(tidyverse) #install.packages("tidyverse")
```

#Read data

This is the gapminder dataset.

```{r}
## read gapminder csv. Note the readr:: prefix identifies which package it's in
gapminder <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv')

#inspect dataset
gapminder #looks at all data
head(gapminder) #gives you the first 6 rows by default
tail(gapminder) #last observations, default is 6

head(gapminder, 3)
tail(gapminder, 10)

#summary statistics
str(gapminder) #structure of data: variables, char/num
summary(gapminder)

#install.packages("skimr")
skimr::skim(gapminder)

names(gapminder) #column names
dim(gapminder) #dimensions
ncol(gapminder) #number of columns
nrow(gapminder) #number of rows

#reverse-engineer dim
c(nrow(gapminder), ncol(gapminder)) #can commbine data steps

```


##Dplyr!

```{r}
#filter by rows
filter(gapminder, lifeExp < 29)
filter(gapminder, country == "Mexico")
filter(gapminder, country %in% c("Mexico", "Peru", "United States"))
filter(gapminder, country == "Mexico", year == 2002)

Sweden <- filter(gapminder, country == "Sweden")
mean(Sweden$lifeExp) #mean life expectancy for Sweden


```

```{r}
#select by columns
select(gapminder, year, lifeExp)
select(gapminder, -continent, -lifeExp) # - will exclude columns

#use select and filter together
gap_cambodia <- filter(gapminder, country == "Cambodia")
gap_cambodia2 <- select(gap_cambodia, -continent, -lifeExp)

```

#Pipe operator

```{r}

gapminder %>% head(3)
# is equivalent to: 
head(gapminder, 3)

#let's improve this with pipes:
gap_cambodia <- filter(gapminder, country == "Cambodia")
gap_cambodia2 <- select(gap_cambodia, -continent, -lifeExp)

gap_cambodia <- gapminder %>% 
  filter(country == "Cambodia") %>% 
  select(-continent, -lifeExp)

```

```{r}
#mutate adds new variables
gapminder %>% 
  mutate(index = 1:nrow(gapminder))
  

gapminder %>% 
  mutate(planet = "Earth")

gapminder %>% 
  mutate(gdp = pop * gdpPercap)

##example:
# Find the maximum gdpPerCap of Egypt and Vietnam. Create a new column. (I want just one number that is the max of those two countries)

gapminder %>% 
  filter(country %in% c("Egypt", "Vietnam")) %>%
  mutate(maxGDP = max(gdpPercap))

```


